// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sportshop.Persistence.Context;

#nullable disable

namespace Sportshop.Persistence.Migrations
{
    [DbContext(typeof(SportshopDbContext))]
    partial class SportshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sportshop.Entity.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ff15c44-abbb-48b8-9b36-dfd2157a5607"),
                            Age = 21,
                            City = "City1",
                            FirstName = "Jan",
                            LastName = "Nowak",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("e65ac179-5bd6-4356-a1d7-d80b1202b31e"),
                            Age = 22,
                            City = "City2",
                            FirstName = "Andrzej",
                            LastName = "Kowalski",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("e1837a17-5e47-4208-b361-9b561fdd2d30"),
                            Age = 23,
                            City = "City3",
                            FirstName = "Piotr",
                            LastName = "Kowalczyk",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("72aab7ed-ac67-4ca1-bc53-850ef22b37fa"),
                            Age = 24,
                            City = "City4",
                            FirstName = "Kamil",
                            LastName = "Grabak",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("41244f64-995b-40c1-a461-58c6efea0214"),
                            Age = 25,
                            City = "City5",
                            FirstName = "Leon",
                            LastName = "Ziutkiewicz",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User5"
                        },
                        new
                        {
                            Id = new Guid("f0121577-57c6-438e-9733-e5a21160db4c"),
                            Age = 26,
                            City = "City6",
                            FirstName = "Karol",
                            LastName = "Strasburger",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User6"
                        },
                        new
                        {
                            Id = new Guid("d3edc55b-2ad0-47ef-b8ca-8f75c94a4dcd"),
                            Age = 27,
                            City = "City7",
                            FirstName = "Andrzej",
                            LastName = "Kipik",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User7"
                        },
                        new
                        {
                            Id = new Guid("6cf7e814-debc-4ade-8796-fa23f2e898d1"),
                            Age = 28,
                            City = "City8",
                            FirstName = "Marzena",
                            LastName = "Bogacz",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User8"
                        },
                        new
                        {
                            Id = new Guid("7d270d2f-9341-47e4-a731-f8e1d3596ead"),
                            Age = 29,
                            City = "City9",
                            FirstName = "Joanna",
                            LastName = "Leśniewska",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User9"
                        },
                        new
                        {
                            Id = new Guid("468d0c1f-aa07-47e9-be37-656e38c2c692"),
                            Age = 30,
                            City = "City10",
                            FirstName = "Weronika",
                            LastName = "Kalinka",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User10"
                        },
                        new
                        {
                            Id = new Guid("f325b0b4-f490-431e-b505-448a427232c2"),
                            Age = 31,
                            City = "City11",
                            FirstName = "",
                            LastName = "",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User11"
                        },
                        new
                        {
                            Id = new Guid("40c0645b-cac9-46e7-9731-44602c45fbba"),
                            Age = 32,
                            City = "City12",
                            FirstName = "",
                            LastName = "",
                            RefreshToken = "",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "User12"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
